# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: scrapping lambda deloyment

on:
  push:
    branches: [ staging ]


jobs:
  build_staging_service:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: install build dependency
      run: |
        sudo apt-get update
        sudo apt-get install libssl-dev libcurl4-openssl-dev python-dev python3-setuptools python3-wheel python3-testresources
        pip install wheel
    # - name: init env
    #   run: |
    #       bash ./scripts/init_env.sh staging
    #   env:
    #     CONF: staging

    - name: deploy service
      run: |
          make lambda-layer-build
          make lambda-function-build
          make BUCKET=selinium-test-bucket create-stack     
      env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}